In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("Student_Performance.csv")

In [3]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  str
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), str(1)
memory usage: 493.2 KB

In [5]:
df["Extracurricular Activities"].unique()

<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

In [6]:
df["Hours Studied"].unique()

array([7, 4, 8, 5, 3, 6, 2, 1, 9])

In [7]:
df["Extracurricular Activities"] = df["Extracurricular Activities"].replace({"Yes": 1 , "No":0})

In [8]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X = df.drop("Performance Index" , axis=1)
y = df["Performance Index"]

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size=0.2 , random_state=42)

In [12]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error  , mean_squared_error ,r2_score

dt_model = DecisionTreeRegressor(random_state=42)

dt_model.fit(X_train , y_train)

y_pred = dt_model.predict(X_test)

print("mse: " , mean_squared_error(y_test , y_pred))
print("mae: " , mean_absolute_error(y_test , y_pred))
print("r2 score: " , r2_score(y_test , y_pred))

mse:  8.812694444444444
mae:  2.3378333333333337
r2 score:  0.9762195132401258

In [13]:
from sklearn.model_selection import GridSearchCV

In [14]:
param_grid = {
    "max_depth": [3,5,7,10,15,None],
    "min_samples_split": [2,5,10,20],
    "min_samples_leaf": [1,5,10,20]
}

In [15]:
dt = DecisionTreeRegressor(random_state=42)

In [16]:
grid_search = GridSearchCV(estimator=dt , param_grid=param_grid , cv=5 , scoring="r2" , n_jobs = -1)

In [17]:
grid_search.fit(X_train , y_train)

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 7, 10, 15, None],
                         'min_samples_leaf': [1, 5, 10, 20],
                         'min_samples_split': [2, 5, 10, 20]},
             scoring='r2')

In [18]:
best_dt_model = grid_search.best_estimator_
y_pred_tuned = best_dt_model.predict(X_test)

In [19]:
print("En İyi Parametreler:", grid_search.best_params_)
print("Optimize MSE: ", mean_squared_error(y_test, y_pred_tuned))
print("Optimize MAE: ", mean_absolute_error(y_test, y_pred_tuned))
print("Optimize R2 Score: ", r2_score(y_test, y_pred_tuned))

En İyi Parametreler: {'max_depth': 15, 'min_samples_leaf': 10, 'min_samples_split': 2}
Optimize MSE:  5.491278600016987
Optimize MAE:  1.876445584175886
Optimize R2 Score:  0.9851821393711425

In [20]:
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR

In [21]:
scaler = StandardScaler()

In [22]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
svr_model = SVR()

In [25]:
svr_model.fit(X_train_scaled , y_train)

SVR()

In [28]:
y_pred_svr = svr_model.predict(X_test_scaled)

In [29]:
print("SVR MSE: ", mean_squared_error(y_test, y_pred_svr))
print("SVR MAE: ", mean_absolute_error(y_test, y_pred_svr))
print("SVR R2 Score: ", r2_score(y_test, y_pred_svr))

SVR MSE:  5.420640008817883
SVR MAE:  1.8236237575302192
SVR R2 Score:  0.9853727530470547

In [31]:
param_grid_svr = {
    "kernel": ["linear","rbf"],
    "C":[0.1 , 1 , 10],
    "epsilon": [0.1 , 0.5 , 1.0]
}

In [32]:
svr = SVR()

In [33]:
grid_search_svr = GridSearchCV(estimator=svr , param_grid=param_grid_svr , cv=5 , scoring="r2" , n_jobs = -1)

In [35]:
grid_search_svr.fit(X_train_scaled , y_train)

GridSearchCV(cv=5, estimator=SVR(), n_jobs=-1,
             param_grid={'C': [0.1, 1, 10], 'epsilon': [0.1, 0.5, 1.0],
                         'kernel': ['linear', 'rbf']},
             scoring='r2')

In [36]:
best_svr_model = grid_search_svr.best_estimator_
y_pred_tuned_svr = best_svr_model.predict(X_test_scaled)

In [37]:
print("En İyi SVR Parametreleri:", grid_search_svr.best_params_)
print("Optimize SVR MSE: ", mean_squared_error(y_test, y_pred_tuned_svr))
print("Optimize SVR MAE: ", mean_absolute_error(y_test, y_pred_tuned_svr))
print("Optimize SVR R2 Score: ", r2_score(y_test, y_pred_tuned_svr))

En İyi SVR Parametreleri: {'C': 10, 'epsilon': 0.5, 'kernel': 'linear'}
Optimize SVR MSE:  4.081968833089967
Optimize SVR MAE:  1.611204399657157
Optimize SVR R2 Score:  0.9889850707520321